---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
    navbar:
      - {title: "Home", href: "index.html", align: left }
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(plotly)
data("ny_noaa")

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d

ny_noaa = 
  ny_noaa %>% 
  separate(date, into = c("year", "month", "day"), convert = TRUE) %>% 
  mutate(
    tmax = as.numeric(tmax),
    tmin = as.numeric(tmin))
```

Column {data-width=650}
-----------------------------------------------------------------------

### Mean monthly temperature for 3 stations across years for December

```{r echo = FALSE, message = FALSE}
Plot_A = ny_noaa |>
  drop_na() |> 
  group_by(id, year, month) |>  
  filter(month == 12) |>
  filter(id %in% c("USW00014732", "USW00094789","USW00014768")) |> 
  summarize(mean_tmax = mean(tmax, na.rm = TRUE, color = id)) |> 
  ggplot(aes(x = year, y = mean_tmax, group = id, color = id)) + geom_point() + geom_path()

ggplotly(Plot_A)
```

Column {data-width=350}
-----------------------------------------------------------------------

### Count of tmin vs tmax between year of 2000 and 2010
```{r echo = FALSE}
plot_B = 
  ny_noaa |> 
  drop_na() |>
  filter(year %in% c(2000:2010)) |> 
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_hex()

ggplotly(plot_B)
```

### Amount of snowfall(mm) in December-January between 2000 and 2010

```{r echo = FALSE}
plot_C = 
  ny_noaa |>
  filter(year %in% c(2000:2010)) |>
  filter(month %in% c(12, 1)) |> 
  filter(snow < 400, snow > 100) |>
  ggplot(aes(x = as.factor(year), y = snow)) + 
  geom_boxplot() +
  labs(x = "year")

ggplotly(plot_C)
```