---
title: "Introduction"
output: html_document
date: "2024-10-30"
---

This is my website to introduce myself.

I will share my past experience and the work doing now in this website.

I also have another [github account](https://github.com/wshin0326) that I used during undergraduate

I used NOAA data to make my graphs in flexdashboard.

## NOAA Data description

The data to be used for this class were acquired using functions from the rnoaa package. rnoaa is an R package available on CRAN that was constructed specifically to download and tidy data from NOAA. Details of the many functions available as part of this package can be found in the package documention. Specifically, the function ghcnd_stations() acquires a list of all of the GHCND-Daily weather stations and the function meteo_pull_monitors() pulls weather data for one or many station IDs.

The following code was used to acquire the five core variables for all New York state weather stations from January 1, 1981 through December 31, 2010. This code was run on a server computer due to the lengthy processing time required, and can serve as a guide for acquisition of additional GHCN-Daily data. Note that the data are acquired via ftp, so an internet connection is required.


